include_attribute "conda"
include_attribute "kagent"
include_attribute "ndb"
include_attribute "hadoop_spark"
include_attribute "flink"
include_attribute "elastic"
include_attribute "glassfish"
include_attribute "kkafka"
include_attribute "kzookeeper"
include_attribute "hive2"
include_attribute "hopsworks"
include_attribute "kkafka"
include_attribute "kzookeeper"
include_attribute "tensorflow"
include_attribute "livy"
include_attribute "hops"
include_attribute "hops_airflow"
include_attribute "consul"
include_attribute "kube-hops"
include_attribute "onlinefs"

default['kagent']['enabled']                       = "false"

default['setup']['user']                           = "vagrant" 
default['setup']['group']                          = "vagrant" 
default['setup']['download_dir']                   = "/home/vagrant/dist" 
